name: hiberus
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  equatable: ^2.0.5
  go_router: ^14.2.7
  dio: ^5.7.0
  retrofit: ^4.4.0
  retrofit_generator: ^8.2.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.4
  

dev_dependencies:
  build_runner: ^2.4.11
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

